{
 "title": "New dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "content": "# ECFLOW server status (local)" },
  {
   "title": "Aborted tasks",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "aborted_tasks" }
   ]
  },
  {
   "title": "Queued tasks",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 13, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "queued_tasks" }
   ]
  },
  {
   "title": "Running tasks",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "running_tasks" }
   ]
  },
  {
   "title": "List of aborted tasks",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{__name__=~\".*_task$\",label=~\"aborted\"} "
    }
   ]
  },
  {
   "title": "List of queued tasks",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 13, "y": 9 },
   "targets": [
    {
     "expr": "{__name__=~\".*_task$\",label=~\"queued\"} "
    }
   ]
  },
  {
   "title": "General overview of models",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ecflow_mgmodels_2018060700_wavewatch"
    },
    { "expr": "ecflow_mgmodels_2018060700_wrf" },
    {}
   ]
  }
 ]
}